### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by jkabrg** [haowen-xu/donut#1]
What license is this under? Might this be patented?

**Comment by haowen-xu** [comment]
It's hard to say whether or not it would be patented.  The code here is released as a complementary code for the paper, but the license issue is not fully discussed with our commercial partner.  I'd suggest you to get your own version of code according to the paper, if you care about this.  That should not be so difficult, if you try to use my own helper library TFSnippet (https://github.com/haowen-xu/tfsnippet), or its major dependency library ZhuSuan (https://github.com/thu-ml/zhusuan).  Both of these libraries are granted under MIT license.
