### ISSUE TITLE
Module not found error: no module named "tfsnippet.modules"

### ISSUE THREAD

**Issue by GONGYIPOLYU** [haowen-xu/donut#11]

**Comment by lizeyan** [comment]
![image](https://user-images.githubusercontent.com/12494243/56339977-ed1b4000-61e2-11e9-87d4-6297c05c334d.png)

**Comment by GONGYIPOLYU** [comment]
Thank you very much for your reply. I also have another question, how can we know the value of input y: missing point indicators.?
![image](https://user-images.githubusercontent.com/46618843/56411879-cfb6a680-62b4-11e9-8c35-25e2045d2146.png)

**Comment by lizeyan** [comment]
> Thank you very much for your reply. I also have another question, how can we know the value of input y: missing point indicators.?
> ![image](https://user-images.githubusercontent.com/46618843/56411879-cfb6a680-62b4-11e9-8c35-25e2045d2146.png)

Well, I think it is natural to know the missing points in your data. If there is no data at some time points, then it is a missing points. You should impute it with 0 and mark it as a missing point in `input_y`.

**Comment by JiangtaoLiu-Tesia** [comment]
> ![image](https://user-images.githubusercontent.com/12494243/56339977-ed1b4000-61e2-11e9-87d4-6297c05c334d.png)
But I still meet another problem, why?
ERROR: Command errored out with exit status 128: git clone -q https://github.com/thu-ml/zhusuan.git /tmp/pip-req-build-so642ma8 Check the logs for full command output.
