### ISSUE TITLE
关于test score的问题

### ISSUE THREAD

**Issue by liu7e** [haowen-xu/donut#19]
test score返回的是每个窗口的重构概率，即如果我有10个数据点，窗口长度为5，那么将返回6个test score。问题是如何把这6个test score分配到10个数据点上？

**Comment by lizeyan** [comment]
我们只用最后一个点的。每个点的score是它在窗口的最后一个点的时候，那个窗口给出的score。
返回6个score，那就对应的是后6个点的score，前面的点是没有score的。
