### ISSUE TITLE
the length of test_score dosen't match that of length of test_values

### ISSUE THREAD

**Issue by jlin-vt** [haowen-xu/donut#20]
I have 72 `test_values` but the `len(test_score)` is 63(in this case there is no missing values). Why is that? thanks!

**Comment by lizeyan** [comment]
Well, the same issue with #19 . Here I will explain it in English.
Donut reconstructs sliding windows. For each sliding window, only the last point's reconstruct probability is used as its test score. So the first several points, which are never last point in any sliding window, have no test score.
If we use 10 points as a sliding window, then the first 9 points have not test scores.
