### ISSUE TITLE
Is there any demo datasets to try this model?

### ISSUE THREAD

**Issue by linjinjin123** [haowen-xu/donut#4]
Hi, I am interested in your project, I'd like to know is there any demo datasets which I can apply on this model ? Would you please add some datasets to this project？

**Comment by ShawnXiao105** [comment]
Or maybe someone can tell me the sample data to fill `timestamp, values, labels = ...`    Much Thanks

**Comment by haowen-xu** [comment]
@linjinjin123 @ShawnXiao105 You may wait for a few days before I have time to get some sample data.  The original dataset, due to the non-disclosure agreement, cannot be made public.  We have some other dataset available for public disclosure in our laboratory, but may need some time to pick out.

**Comment by lizeyan** [comment]
I pick and upload some KPI data from [a public competation](http://iops.ai/competition_detail/?competition_id=5&flag=1).

**Comment by lizeyan** [comment]
@ShawnXiao105 I am sorry, but as @haowen-xu said, "the original dataset, due to the non-disclosure agreement, cannot be made public". I can only pick some data that are similar to the KPI series we used from public datasets.

**Comment by Huang-yi-3456** [comment]
@lizeyan thanks for uploading 4 example datasets. since all datasets have 3 columns, timestamp, value and label, I was wondering is it a prerequisite? does the project fit a dataset with multiple dimensions (about 6 columns)? Thanks for your time.

**Comment by lizeyan** [comment]
> @lizeyan thanks for uploading 4 example datasets. since all datasets have 3 columns, timestamp, value and label, I was wondering is it a prerequisite? does the project fit a dataset with multiple dimensions (about 6 columns)? Thanks for your time.

I have not tried Donut with multiple dimensions data. Actually in this paper we take care of single dimension series only. You can just try it.
