### ISSUE TITLE
Ellipsis

### ISSUE THREAD

**Issue by versionJX** [haowen-xu/donut#6]
Hi，

I am trying to run your API, but error "TypeError: 'ellipsis' object is not iterable" occurs at 
"# Read the raw data.
timestamp, values, labels = ..."

I searched and found that usually this error occurs at Python 3.5 and no more at Python 3.5.3 or above. My python is 3.5.5. Am i using the API in wrong way or other hints?

Thanks in advance.

**Comment by lizeyan** [comment]
Please paste your code.

**Comment by versionJX** [comment]
i just copied your example code and run.
import numpy as np
from donut import complete_timestamp, standardize_kpi

# Read the raw data.
timestamp, values, labels = ...
# If there is no label, simply use all zeros.
labels = np.zeros_like(values, dtype=np.int32)

# Complete the timestamp, and obtain the missing point indicators.
timestamp, missing, (values, labels) = \
    complete_timestamp(timestamp, (values, labels))

# Split the training and testing data.
test_portion = 0.3
test_n = int(len(values) * test_portion)
train_values, test_values = values[:-test_n], values[-test_n:]
train_labels, test_labels = labels[:-test_n], labels[-test_n:]
train_missing, test_missing = missing[:-test_n], missing[-test_n:]

# Standardize the training and testing data.
train_values, mean, std = standardize_kpi(
    train_values, excludes=np.logical_or(train_labels, train_missing))
test_values, _, _ = standardize_kpi(test_values, mean=mean, std=std)

**Comment by lizeyan** [comment]
I am sorry. Do you mean you run the following code directly?
`timestamp, values, labels = ...`
This line is just a example, `...` means use your own code to read data.

**Comment by versionJX** [comment]
yes, i just run the code directly.
Sorry i have no idea about how to obtain the time series data. Should i load data from the csv file from your sample_data folder?

**Comment by lizeyan** [comment]
Take a look at 'pandas'.
``` python3
import pandas as pd
df = pd.read_csv(csv_file_path)
timestamp, values, labels = df["timestamp"], df["value"], df["label"]
```

**Comment by versionJX** [comment]
> Take a look at 'pandas'.
> 
> ```python
> import pandas as pd
> df = pd.read_csv(csv_file_path)
> timestamp, values, labels = df["timestamp"], df["value"], df["label"]
> ```
Thanks a lot, now it works.
